WILMS/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import ReactAppView
from wallet import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from .views import serve_manifest


from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('wallet/', include('wallet.urls', namespace='wallet')),  # Include app-specific URLs with the 'wallet' namespace
    path('walletAPI/', include(('walletAPI.urls', 'walletAPI'), namespace='walletAPI')),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('wiladmin/', include('wiladmin.urls')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('' , views.IndexView.as_view(), name='index'),
    path('facility/', include('facility.urls')),

    re_path(r'^manifest\.json$', serve_manifest),
    
    
    
    path('logout/',views.UserLogoutView.as_view(),name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='wallet/password_reset.html'), name="password_reset"),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='wallet/password_reset_done.html'), name = "password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='wallet/password_reset_confirm.html'), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='wallet/password_reset_complete.html'), name='password_reset_complete'),

# for api front end
    path('booking/login/', ReactAppView.as_view(), name='login'),
    # path('', ReactAppView.as_view(), name='login'),  # Uncomment this line if you want / to point to the login page
    path('booking/tracker/', ReactAppView.as_view(), name='tracker'),
    path('booking/calendar/', ReactAppView.as_view(), name='calendar'),
    path('booking/logs/', ReactAppView.as_view(), name='attendance_logs'),
    path('booking/bookings/', ReactAppView.as_view(), name='my_reservations'),
    path('attendance/', ReactAppView.as_view(), name='attendance'),
    path('booking/attendance/', ReactAppView.as_view(), name='booking_attendance'),
    path('react/', ReactAppView.as_view(), name='react_app'),


    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from .views import *
from api.controllers.calendarController import CalendarController
from api.controllers.bookingController import BookingController
from api.controllers.detailsController import DetailsController
from api.controllers.managementController import ManagementController
from api.controllers.dashboardController import DashboardController
from api.controllers.logsController import *
from api.controllers.tapController import TapController
from api.controllers.logsController import LogsController
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
urlpatterns = [
    # path('booking/',BookingDetail.as_view(),name='creation'),
    # path('currentBookings/',CurrentBookings.as_view(),name='currentBookings'),
    # path('getBookingByVenue/<id>/',BookingByVenue.as_view(),name='bookingsByVenue'),
    # path('booking/',BookingDetail.as_view(),name='creation'),

    ##Calendar controllers
    path('createBooking/',CalendarController.saveBooking,name='create booking'),
    path('currentBookings/',CalendarController.getCurrentBookings,name='current bookings'),
    path('getEvents/', CalendarController.getEvents, name='get events'),
    ##Controllers na wa pa na separate
    path('getAttendees/<id>/',AttendeeDetail.as_view(),name='getBookingAttendees'),
    path('users/',Users.as_view(),name='getAllUsers'),

    #view details na controller
    path('cancelBooking/<id>',DetailsController.cancelBooking,name="cancelbooking"),

    #booking creation controller
    path('calculateCost/<venue_id>',BookingController.calculateCost,name="calculate payment or cost"),
    path('getUsers/',BookingController.getAllUsers,name="get all users"),

    #booking management controller
    #admin view sa booking management
    path('getDurations/',BookingController.getDurations,name="calculate total hour for users"),
    path('getAllBookings/',ManagementController.getAllBooking,name="get all bookings"),
    path('getAllCancelledBookings/',ManagementController.getAllCancelledBooking,name="get all cancelled bookings"),
    path('getAllNoShowBookings/',ManagementController.getAllNoShowBooking,name="get all no show bookings"),
    #for non admin or normal users  
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('getAllUserBookings/<user_id>/',ManagementController.getAllUserBookings,name="get booking of user"),
    path('getUpcomingUserBookings/<user_id>/',ManagementController.getUpcomingUserBookings,name="get upcoming bookings of user"),
    path('getHistoryUserBookings/<user_id>/',ManagementController.getHistoryUserBookings,name="get user bookings in the past"),
    #for editting
    path('deleteAttendee/<attendee_id>/',ManagementController.removeBookingAttendee,name="remove attendee"),
    path('addAttendee/<booking_id>/',ManagementController.addBookingAttendee,name="add attendee for booking"),
    path('editBooking/<booking_id>/',ManagementController.editBooking,name="update booking details"),
    #for tap or sign in
    path('logAttendance/',TapController.logAttendance,name="tapping or sign in"),
    #for dashboard
    path('getSignedIn/',DashboardController.getSignedIn,name='get all signed in currently in facilities'),
    path('getExpected/',DashboardController.getExpected,name="get all expected count for each facility"),
    path('getWaiting/',DashboardController.getWaiting,name="get all waiting for bookings"),
    path('getOngoing/',DashboardController.getOngoing,name="get all ongoing"),
    path('getOverstaying/',DashboardController.getOverstaying,name="get overstaying beyond their booking"),
    path('login/',login,name='login'),
    path('signup/',signup,name='signup'),
    #for logs page
    path('getAllAttendance/',LogsController.getAllAttendance, name="get all attendance"),



    # kirk added

    path('react/', ReactAppView.as_view(), name='react_app'),
]

polls/urls.py
from django.urls import path
from .views import insert_into_database, show_message_view
from django.contrib import admin
from . import views
from . import user_login_controller
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('wiluser/map/', views.map, name='map'),
    path('area_button_click/', views.area_button_click, name='areaButtonClick'),
    path('wiluser/location/', views.location, name='location'),
    path('wiluser/activebooking/', views.ActiveBookingController.as_view(), name='activebooking'),
    path('wiluser/timer/', views.timer, name='timer'),
    path('insert-into-database/', insert_into_database, name='insertIntoDatabase'),
    path('show_message/', show_message_view, name='show_message'),
    path('wiluser/userlogin/', user_login_controller.UserLoginController.as_view(), name='user_login'),
    path('wiluser/userlogout/', views.user_logout, name='user_logout'),
    path('wiluser/userdashboard/', views.user_dashboard, name='userdashboard'),
    path('wiluser/userprofile/', views.user_profile, name='userprofile'),
    path('admin/', admin.site.urls),
    path('get_timer_data/', views.get_timer_data, name='get_timer_data'),
    path('end_session/', views.end_session_view, name='end_session'),
    path('get-booking-info/', views.get_booking_info, name='get_booking_info'),
    path('get-reservebooking-info/', views.get_reservebooking_info, name='get_reservebooking_info'),
    path('get-calendar-data/', views.get_calendar_data, name='get_calendar_data'),
    path('wiluser/activewalkinbooking/', views.activewalkinbooking, name='activewalkinbooking'),
    path('wiluser/walkin-booking-history/', views.walkin_booking_history, name='walkinbookinghistory'),
    
]

polls/models.py
from django.db import models

class AssignedArea(models.Model):
    reference_number = models.CharField(max_length=100)
    area_id = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.reference_number+" - "+self.area_id
    

class UserAccountModel(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
        
    def __str__(self):
        return self.username


class Timer(models.Model):
    minutes = models.IntegerField(default=30)
    seconds = models.IntegerField(default=0)
    session_ended = models.BooleanField(default=False)
    user_id = models.CharField(primary_key=True, max_length=20)

    def __str__(self):
        return f"Timer for User ID {self.user_id}"




class Booking(models.Model):
    reserved_id = models.AutoField(primary_key=True)
    reference_number = models.CharField(max_length=10)
    area_id = models.CharField(max_length=5)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    user_id = models.CharField(max_length=20)
    status = models.CharField(max_length=20)

polls/templates/wil/activebooking.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/userdashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/WILLOGO.png' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" />


    {% block extra_css %}{% endblock %}
</head>
<body style="background-color: #FECC00;">
    <div class="content">
        <div class="header">
            <div >
                <a href="{% url 'polls:userprofile' %}">
                    <img src="{% static 'images/profile.png' %}" alt="Profile Icon" class="profile-icon" style="width: 32px; height: 32px; margin-right:60px">
                </a>
                
                </a>
                
                 <img src="{% static 'images/WILLOGO.png' %}" alt="WIL LOGO" class="logo" style="margin-right:100px; border: 2px solid #000000;">
                
            </div>
    <div class="arealocation-container" style = "color:#ffffff; background-color:#000000; border: 1px solid #ffffff; height:220px">
        <div class="button-overlay">
            <div class="mobile-buttons">
                {% if area_id %}
                <h3>ASSIGNED AREA: <span style="color: red; text-decoration: underline;">{{ area_id }}</span></h3>
                {% else %}
                <h4>Assigned Area: N/A</h4>
                {% endif %}
            </div>

            <div class="image-container">

                <img src="{% static 'images/area.png' %}" alt="area" class="image-fit"/>
                {% if area_id == "A1" %}
                <button class="areaA1-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A2" %}
                <button class="areaA2-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A3" %}
                <button class="areaA3-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A4" %}
                <button class="areaA4-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A5" %}
                <button class="areaA5-button"><i class="fas fa-map-marker-alt"></i></button>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="location-container" style="background-color:#ffffff; color:#000000; border: 1px solid #000000;">
        <div class="mobile-screen">
            {% block content %}
            {% endblock %}
        </div>

        <div class="mobile-buttons">
            <h4>GUIDELINES</h4>

            <div>
                <h5>You arleady have an existing reservation on {{date}}</h5>
                <h5> Please proceed to the front desk and confirm your booking </h5>
                <br>
                Reference Number: <font color="red">{{reference_number}}</font>
                <br>
            </div>

        </div>

    </div>


    <script>

        document.querySelector('.time-button').addEventListener('click', function() {

            window.location.href = "{% url 'polls:timer' %}";
        });
    </script>
</body>
</html>

polls/templates/wil/activewalkinbooking.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pending</title>
    <link rel="stylesheet" href="{% static 'css/userdashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/WILLOGO.png' %}">
</head>
<body style="background-color: #FECC00;"> 
    <div class="content">
        <div class="header">
            <div >
                <a href="/polls/wiluser/userprofile">
                    <img src="{% static 'images/profile.png' %}" alt="Profile Icon" class="profile-icon" style="width: 32px; height: 32px; margin-right:60px">
                </a>
                 <img src="{% static 'images/WILLOGO.png' %}" alt="WIL LOGO" class="logo" style="margin-right:100px; border: 2px solid #000000;">
            </div>
            <div class="area-container" style = " background-color:#000000; border: 1px solid #ffffff; height:230px">
                <div class="mobile-buttons">
                    
                <p>You already have a pending booking. Please proceed to the front desk and present your walk-in reference number below.</p>
                Reference Number:&nbsp<font color="red">{{ reference_id }}</font>
                    
                </div>
            </div>
            <br>
            <div class="guidelines-container" style="background-color:#000000; color:#ffffff; border: 1px solid #ffffff;">
                <div class="mobile-screen">
                    {% block content %}
                    {% endblock %}
                </div>
                <div class="mobile-buttons">
                    <h5>GUIDELINES</h5>
                    <div>
                         <h3>WALK-IN BOOKING</h3>
                    </div>
                    <div>
                         <h4>1. Select an available area within the facility map</h4>
                         <h4>2. Confirm your selected area</h4>
                         <h4>3. Present walk-in reference number to the front desk</h4>
                    </div>
                </div>
            </div>
        </div>
    
   

    
</body>
</html>

polls/templates/wil/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome to the Home Page</h1>
<p>This is the content of the home page.</p>
{% endblock %}

polls/templates/wil/location.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/userdashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/WILLOGO.png' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" />


    {% block extra_css %}{% endblock %}
</head>
<body style="background-color: #FECC00;">
    <div class="content">
        <div class="header">
            <div >
                <a href="{% url 'polls:userprofile' %}">
                    <img src="{% static 'images/profile.png' %}" alt="Profile Icon" class="profile-icon" style="width: 50px; height: 50px; margin-right:46px; position: relative; right: 20px;">
                </a>
                
                </a>
                
                 <img src="{% static 'images/WILLOGO.png' %}" alt="WIL LOGO" class="logo" style="margin-right:100px; border: 2px solid #000000;">
                
            </div>
    <div class="arealocation-container" style = "color:#ffffff; background-color:#000000; border: 1px solid #ffffff; height:220px">
        <div class="button-overlay">
            <div class="mobile-buttons">
                {% if area_id %}
                <h3>ASSIGNED AREA: <span style="color: red; text-decoration: underline;">{{ area_id }}</span></h3>
                {% else %}
                <h4>Assigned Area: N/A</h4>
                {% endif %}
            </div>

            <div class="image-container">

                <img src="{% static 'images/area.png' %}" alt="area" class="image-fit"/>
                {% if area_id == "A1" %}
                <button class="areaA1-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A2" %}
                <button class="areaA2-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A3" %}
                <button class="areaA3-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A4" %}
                <button class="areaA4-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A5" %}
                <button class="areaA5-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A6" %}
                <button class="areaA6-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A7" %}
                <button class="areaA7-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A8" %}
                <button class="areaA8-button"><i class="fas fa-map-marker-alt"></i></button>
                {% elif area_id == "A9" %}
                <button class="areaA9-button"><i class="fas fa-map-marker-alt"></i></button>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="location-container" style="background-color:#ffffff; color:#000000; border: 1px solid #000000;" >
        <div class="mobile-screen">
            {% block content %}
            {% endblock %}
        </div>

        <div class="mobile-buttons">
            <h3>GUIDELINES</h3>

            <div>
                 <h4>TIME MONITORING</h4>
                 <ol style="text-align:left; margin:5px">
                    <li>Once your walk-in booking has been confirmed, you are automatically credited time</li>
                    <li>Use the facility map to locate your area.</li>
                    <li>To view your running time, click the time monitoring button</li>
                 </ol>
                 <br>
                <br>
                <br>
                <button class="time-button"  style = "color:#ffffff; background-color:#000000; border: 2px solid #ffffff;">TIME MONITORING</button>
            </div>

        </div>

    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        document.querySelector('.time-button').addEventListener('click', function() {

            window.location.href = "{% url 'polls:timer' %}";
        });
    </script>
    
    <script>
        function updateTimer() {
            $.ajax({
                url: '{% url "polls:get_timer_data" %}',
                dataType: 'json',
                success: function (data) {
                    if (!data.session_ended) {
                        var formattedTime = data.minutes.toString().padStart(2, '0') + ':' + data.seconds.toString().padStart(2, '0');
                        $('#timer').text(formattedTime);
                        if (data.minutes === 0 && data.seconds === 0) {
                            showNotification("WILDSPACE", "Your time has ended!");
                        }
                    } else {
                        $('#timer').text('00:00');
                    }
                }
            });
        }

        $(document).ready(function() {
            updateTimer(); 
            setInterval(updateTimer, 1000); 
        });
    </script>
</body>
</html>

polls/templates/wil/timer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" />
    {% block extra_css %}{% endblock %}
</head>
<body style="background-color: #FECC00;">
<a href="{% url 'polls:location' %}" class="left-button"><i class="fas fa-arrow-left"></i></a>
<div>
<div class="name-container" style="background-color:#000000">
  <div>
    <h4 >Welcome {{ user.email }}</h4>
  </div>
  <div class="button-overlay"></div>
</div>  
<br>
<div class="reminders-container" style="background-color:#000000; color:#ffffff">
    <div class="">
        <div class="mobile-buttons">
          <h4 STYLE="text-align: left">Reminders for WILDSPACE:</h4>
        </div>
        <ul style="font-size: 13.5px">
          <li>Always be mindful of your surroundings and others around you.</li>
          <li>Stay on the area you are assigned to.</li>
          <li>Once your time is up, proceed to the front desk for end session confirmation.</li>
        </ul>
        <div class="">
        </div>
    </div>
</div>
<br>
<div class="information-container" style="background-color:#000000; color:#ffffff; border: 1px solid #ffffff">
    <div class="mobile-screen">
        {% block content %}
        {% endblock %}
    </div>
    <h3 style="text-align:center;">WILDSPACE INFORMATION</h3>
    <br>
    <div>
      <h4>User Id: <span style="color: red; text-decoration: ">{{ id_number }}</span></h4>
      <h4>Booking Reference ID: <span style="color: red; text-decoration: ">{{ booking_reference_number }}</span></h4>
      <h4>Assigned Area: <span style="color: red; text-decoration: ">{{ assigned_area }}</span></h4>
      <h4>Date of Use: <span style="color: red; text-decoration: ">{{ date_of_use }}</span></h4>      
      <h4>Booking type: <span style="color: red; text-decoration: ">Walk-in</span></h4>

    </div>
    <br>

    <div class="time-container" style="background-color:#ffffff;border: 1px solid #000000"> 
      <h4 id="timer">00:00</h4>
    </div>
    <br>
    <br>
    <button class="end-button">END SESSION</button>
</div>
</div>

<div id="confirmation-dialog" class="confirmation-dialog">
  <h2>Confirmation</h2>
  <p>Are you sure you want to end the session?</p>
  <div class="button-container">
    <button id="confirm-button">Yes</button>
    <button id="cancel-button">No</button>
  </div>
</div>
<div id="overlay" class="overlay"></div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  if ("Notification" in window) {
      if (Notification.permission !== "granted") {
        Notification.requestPermission().then(function (permission) {
          
        });
      }
    }
    
  
    function updateTimer() {
      $.ajax({
          url: '{% url "polls:get_timer_data" %}',
          dataType: 'json',
          success: function(data) {
              if (!data.session_ended) {
                  var formattedTime = padNumber(data.minutes) + ':' + padNumber(data.seconds);
                  $('#timer').text(formattedTime);
                  
                  if (data.minutes === 3 && data.seconds === 0) {
                      showNotification("WARNING WILDSPACE", "You only have 3 minutes left!");
                  }
                  
                  if (data.minutes === 0 && data.seconds === 0) {
                      showNotification("WILDSPACE", "Your time has ended!");
                      
                      displayMessageOverlay('{{ booking_reference_number }}');
                  }
              } else {
                  $('#timer').text('00:00');
              }
          }
      });
  }
  
  
  function displayMessageOverlay(referenceNumber) {
      var messageOverlay = document.createElement('div');
      messageOverlay.classList.add('message-overlay');
  
      var messageBox = document.createElement('div');
      messageBox.classList.add('message-box');
  
      var messageHeader = document.createElement('h2');
      messageHeader.textContent = 'Session Ended';
  
      var messageContent = document.createElement('p');
      messageContent.innerHTML = 'Reference Number: ' + referenceNumber;
  
      var additionalText = document.createElement('p');
      additionalText.textContent = 'To avoid overstaying charges, please go to the front desk and present your reference number to confirm that your allotted time has ended.';
  
      messageBox.appendChild(messageHeader);
      messageBox.appendChild(messageContent);
      messageBox.appendChild(additionalText);
  
      messageOverlay.appendChild(messageBox);
  
      document.body.appendChild(messageOverlay);
  
      $('#timer').text('00:00');
      hideConfirmationDialog();
  }
  
    function showNotification(title, body) {
      if (Notification.permission === "granted") {
        var options = {
          body: body,
        };
    
        var notification = new Notification(title, options);
    
      
        notification.onclick = function () {
          
          notification.close();
        };
      }
    }
    

function padNumber(number) {
    return number.toString().padStart(2, '0');
}


function showConfirmationDialog() {
  var confirmationDialog = document.getElementById('confirmation-dialog');
  var overlay = document.getElementById('overlay');
  confirmationDialog.style.display = 'block';
  overlay.style.display = 'block';
}


document.getElementById('confirm-button').addEventListener('click', confirmEndSession);
document.getElementById('cancel-button').addEventListener('click', cancelEndSession);


function confirmEndSession() {
  
  var csrfToken = getCookie('csrftoken');

  $.ajax({
      url: '{% url "polls:end_session" %}',  
      method: 'POST',
      data: {session_ended: true},
      headers: {
          "X-CSRFToken": csrfToken  
      },
      success: function(data) {
          
          if (data.success) {
              
              var referenceNumber = '{{ booking_reference_number }}';
              var messageOverlay = document.createElement('div');
              messageOverlay.classList.add('message-overlay');

              var messageBox = document.createElement('div');
              messageBox.classList.add('message-box');

              var messageHeader = document.createElement('h2');
              messageHeader.textContent = 'Session Ended';

              var messageContent = document.createElement('p');
              messageContent.innerHTML = 'Reference ID: ' + referenceNumber;

              var additionalText = document.createElement('p');
              additionalText.textContent = 'To avoid overstaying charges, please go to the front desk and present your reference number to confirm that your allotted time has ended.';

              messageBox.appendChild(messageHeader);
              messageBox.appendChild(messageContent);
              messageBox.appendChild(additionalText);

              messageOverlay.appendChild(messageBox);

              document.body.appendChild(messageOverlay);

              
              $('#timer').text('00:00');

              
              hideConfirmationDialog();
          } else {
              alert('Failed to end the session. Please try again.');
          }
      },
      error: function(xhr, textStatus, errorThrown) {
          console.log(xhr.responseText); 
          alert('Failed to end the session. Please try again.');
      }
  });
}



function getCookie(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
          }
      }
  }
  return cookieValue;
}



function cancelEndSession() {
  
  hideConfirmationDialog();
}


function hideConfirmationDialog() {
  var confirmationDialog = document.getElementById('confirmation-dialog');
  var overlay = document.getElementById('overlay');
  confirmationDialog.style.display = 'none';
  overlay.style.display = 'none';
}

$(document).ready(function() {
    setInterval(updateTimer, 1000);
});


document.querySelector('.end-button').addEventListener('click', function() {
  showConfirmationDialog();
});



</script>

</body>
</html>

polls/templates/wil/userprofile.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/userdashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/WILLOGO.png' %}">
</head>

<body >
    <div class="content">
        <a href="/polls/wiluser/userdashboard" >
            <img src="{% static 'images/arrow.png' %}" alt="Back Arrow Icon" class="back-icon" style="width: 32px; height: 32px;">
        </a>
        <h1> My Profile </h1>
        
            
            <div class="buttonContainer">
                <div class="area-container" style="width:220px; height: 50px; background-color:#FFFF00">
                    <div class="button-overlay">
                        <div class="mobile-buttons">
                            
                        </div>
                        <div class="">
                            <div>
                                <img src="{% static 'images/profile.png' %}" alt="Profile Icon" class="profile-icon" style="width: 50px; height: 50px; margin-right: 20px; margin-top: -200px;" >
                                <span style="color: black; font-size:15px">{{ user.email }}</span>
                                </img>
                            
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <br>
                <a href="{% url 'polls:walkinbookinghistory' %}"  >
                    <button type="submit" class="button">WALK-IN HISTORY</button>

                    </a>
                <br>
               
                <a href="/wallet/">
                    <button type="submit" class="button">RETURN TO MENU</button>
                </a>
                
               
            </div>
    </div>
</body>

</html>