WILMS/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import ReactAppView
from wallet import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from .views import serve_manifest


from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('wallet/', include('wallet.urls', namespace='wallet')),  # Include app-specific URLs with the 'wallet' namespace
    path('walletAPI/', include(('walletAPI.urls', 'walletAPI'), namespace='walletAPI')),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('wiladmin/', include('wiladmin.urls')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('' , views.IndexView.as_view(), name='index'),
    path('facility/', include('facility.urls')),

    re_path(r'^manifest\.json$', serve_manifest),
    
    
    
    path('logout/',views.UserLogoutView.as_view(),name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='wallet/password_reset.html'), name="password_reset"),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='wallet/password_reset_done.html'), name = "password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='wallet/password_reset_confirm.html'), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='wallet/password_reset_complete.html'), name='password_reset_complete'),

# for api front end
    path('booking/login/', ReactAppView.as_view(), name='login'),
    # path('', ReactAppView.as_view(), name='login'),  # Uncomment this line if you want / to point to the login page
    path('booking/tracker/', ReactAppView.as_view(), name='tracker'),
    path('booking/calendar/', ReactAppView.as_view(), name='calendar'),
    path('booking/logs/', ReactAppView.as_view(), name='attendance_logs'),
    path('booking/bookings/', ReactAppView.as_view(), name='my_reservations'),
    path('attendance/', ReactAppView.as_view(), name='attendance'),
    path('booking/attendance/', ReactAppView.as_view(), name='booking_attendance'),
    path('react/', ReactAppView.as_view(), name='react_app'),


    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from .views import *
from api.controllers.calendarController import CalendarController
from api.controllers.bookingController import BookingController
from api.controllers.detailsController import DetailsController
from api.controllers.managementController import ManagementController
from api.controllers.dashboardController import DashboardController
from api.controllers.logsController import *
from api.controllers.tapController import TapController
from api.controllers.logsController import LogsController
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
urlpatterns = [
    # path('booking/',BookingDetail.as_view(),name='creation'),
    # path('currentBookings/',CurrentBookings.as_view(),name='currentBookings'),
    # path('getBookingByVenue/<id>/',BookingByVenue.as_view(),name='bookingsByVenue'),
    # path('booking/',BookingDetail.as_view(),name='creation'),

    ##Calendar controllers
    path('createBooking/',CalendarController.saveBooking,name='create booking'),
    path('currentBookings/',CalendarController.getCurrentBookings,name='current bookings'),
    path('getEvents/', CalendarController.getEvents, name='get events'),
    ##Controllers na wa pa na separate
    path('getAttendees/<id>/',AttendeeDetail.as_view(),name='getBookingAttendees'),
    path('users/',Users.as_view(),name='getAllUsers'),

    #view details na controller
    path('cancelBooking/<id>',DetailsController.cancelBooking,name="cancelbooking"),

    #booking creation controller
    path('calculateCost/<venue_id>',BookingController.calculateCost,name="calculate payment or cost"),
    path('getUsers/',BookingController.getAllUsers,name="get all users"),

    #booking management controller
    #admin view sa booking management
    path('getDurations/',BookingController.getDurations,name="calculate total hour for users"),
    path('getAllBookings/',ManagementController.getAllBooking,name="get all bookings"),
    path('getAllCancelledBookings/',ManagementController.getAllCancelledBooking,name="get all cancelled bookings"),
    path('getAllNoShowBookings/',ManagementController.getAllNoShowBooking,name="get all no show bookings"),
    #for non admin or normal users  
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('getAllUserBookings/<user_id>/',ManagementController.getAllUserBookings,name="get booking of user"),
    path('getUpcomingUserBookings/<user_id>/',ManagementController.getUpcomingUserBookings,name="get upcoming bookings of user"),
    path('getHistoryUserBookings/<user_id>/',ManagementController.getHistoryUserBookings,name="get user bookings in the past"),
    #for editting
    path('deleteAttendee/<attendee_id>/',ManagementController.removeBookingAttendee,name="remove attendee"),
    path('addAttendee/<booking_id>/',ManagementController.addBookingAttendee,name="add attendee for booking"),
    path('editBooking/<booking_id>/',ManagementController.editBooking,name="update booking details"),
    #for tap or sign in
    path('logAttendance/',TapController.logAttendance,name="tapping or sign in"),
    #for dashboard
    path('getSignedIn/',DashboardController.getSignedIn,name='get all signed in currently in facilities'),
    path('getExpected/',DashboardController.getExpected,name="get all expected count for each facility"),
    path('getWaiting/',DashboardController.getWaiting,name="get all waiting for bookings"),
    path('getOngoing/',DashboardController.getOngoing,name="get all ongoing"),
    path('getOverstaying/',DashboardController.getOverstaying,name="get overstaying beyond their booking"),
    path('login/',login,name='login'),
    path('signup/',signup,name='signup'),
    #for logs page
    path('getAllAttendance/',LogsController.getAllAttendance, name="get all attendance"),



    # kirk added

    path('react/', ReactAppView.as_view(), name='react_app'),
]

wallet/urls.py
from django.urls import path
from wallet.views import AccountStatusView, GetUserStatusView, IndexView, RegisterView, UserLoginView, DashboardView, UserListView,UserLogoutView,UserDashboardView,PointsDashboardView, TransactionApprovalView,SuccessRedirectView,CoinTransactionCreateAndDashboardView,GetTransactionDetailsView,SettingsView,ChangePasswordView, UpdateAccountTypeView, TeacherUserListView, AdminAwardPointsToTeacherView, ActivateAccountView,ScanAndDisplayRFIDView,EditUserProfileView
# Increment 2
from django.conf import settings
from django.conf.urls.static import static  

from django.contrib.auth import views as auth_views

from . import views

app_name = 'wallet'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),  
    path('user_list/', UserListView.as_view(), name='userlist'),
    # path('store_transaction/', StoreTransactionView.as_view(), name='store_transaction'),
    path('logout/',UserLogoutView.as_view(),name='logout'),
    path('usrdashboard/', UserDashboardView.as_view(), name='usrdashboard'), 
    path('pdash/',PointsDashboardView.as_view(),name='pointsdash'),
    # INCREMENT 2
    path('createCoin/', CoinTransactionCreateAndDashboardView.as_view(), name='create-coin-transaction'),
    
    path('request/approval/', TransactionApprovalView.as_view(), name='request-approval'),
    path('success/',SuccessRedirectView.as_view(),name='success'),

    path('request/approval/approve-transaction/', views.approve_transaction, name='approve-transaction'),
    path('request/approval/deny-transaction/', views.deny_transaction, name='deny-transaction'),
    path('request/approval/get-transaction-details/', GetTransactionDetailsView.as_view(), name='get_transaction_details'),

    # INCREMENT 3
    path('settings/',SettingsView.as_view(),name='settings'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),

    # INCREMENT 4
    path('update_account_type/<int:id>/', UpdateAccountTypeView.as_view(), name='update_account_type'),
    path('teacher_user_list/', TeacherUserListView.as_view(), name='teacheruserlist'),

    # BONUS CONTENT
    path('award_points_to_teacher/', views.AdminAwardPointsToTeacherView.as_view(), name='award_points_to_teacher'),


    # RFID
    path('activate_account/', ActivateAccountView.as_view(), name='activate_account'),

    # GRAB VALUES
    path('scan/', ScanAndDisplayRFIDView.as_view(), name='scan'),

    # EDIT PROFILE
    path('edit_profile/', EditUserProfileView.as_view(), name='edit_profile'),

    #ACCOUNT Status
    path('account_status/<int:user_id>/', AccountStatusView.as_view(), name='account_status'),
    path('get_user_status/<int:user_id>/', GetUserStatusView.as_view(), name='get_user_status'),

  





    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wallet/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.conf import settings
import uuid


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.user_type='admin'
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    STUDENT = 'student'
    TEACHER = 'teacher'
    ADMIN = 'admin'

    USER_TYPES = [
        (STUDENT, 'Student'),
        (TEACHER, 'Teacher'),
        (ADMIN, 'Admin'),
    ]

    email = models.EmailField(unique=True)
    user_type = models.CharField(max_length=10, choices=USER_TYPES, default=STUDENT)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)  # Set default to True for students
    is_verified = models.BooleanField(default=False)
    is_disabled = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        swappable = 'AUTH_USER_MODEL'
        default_related_name = 'wallet_users'

    
class UserProfileInfo(models.Model):
    profile_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    coin_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    point_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    points_to_give = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    rfid_value = models.CharField(max_length=50,unique=True, blank=True, null=True)  # Add this field for storing RFID values


    def __str__(self):
        return self.user.email



class Transaction(models.Model):
    transactionID = models.AutoField(primary_key=True)
    recipient = models.ForeignKey(User,related_name='transaction_reciepient', on_delete=models.CASCADE)
    sender = models.ForeignKey(User,related_name='transaction_sender', on_delete=models.CASCADE)
    points = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.transactionID)
    
class CoinTransaction(models.Model):
    reference_code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    requestee = models.ForeignKey(User, related_name='coin_transactions_requested', on_delete=models.CASCADE)
    amount = models.FloatField(default=0.0)
    image_receipt = models.ImageField(upload_to='coin_transaction_receipts/')
    date_in_receipt = models.DateField()
    is_completed = models.BooleanField(default=False)
    is_denied = models.BooleanField(default=False)

    @property
    def is_pending(self):
        return not self.is_completed and not self.is_denied

    def __str__(self):
        return str(self.reference_code)



# Bonus Content

class AdminPointAward(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='admin_point_awards')
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='admin_received_point_awards')
    points_awarded = models.DecimalField(max_digits=10, decimal_places=2)
    date_awarded = models.DateTimeField(auto_now_add=True)
    # Add any other relevant fields

wallet/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserProfileInfo, CoinTransaction
from django.core.validators import MinValueValidator

User = get_user_model()

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = UserProfileInfo
        fields = ('first_name', 'last_name', 'confirm_password')
        widgets = {
            'password': forms.PasswordInput(),
        }

# INCREMENT 2

class CoinTransactionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CoinTransactionForm, self).__init__(*args, **kwargs)

        if user:
            self.fields['requestee'].initial = user

        self.fields['requestee'].widget = forms.HiddenInput()

    class Meta:
        model = CoinTransaction
        fields = ['requestee', 'amount', 'image_receipt', 'date_in_receipt']

        widgets = {
            'amount': forms.NumberInput(attrs={'min': 1}),  # Set the minimum value for the amount field
        }

        validators = {
            'amount': [MinValueValidator(1)],  # Another way to set the minimum value for the amount field
        }



class TransactionApprovalForm(forms.ModelForm):
    ACTION_CHOICES = (
        ('approve', 'Approve'),
        ('deny', 'Deny'),
    )
    
    action = forms.ChoiceField(choices=ACTION_CHOICES, widget=forms.RadioSelect)
    reference_code = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = CoinTransaction
        fields = []  # No fields from the model, as this form is only for the action choice


class UserProfileInfoUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('first_name', 'last_name', 'profile_picture')

wallet/templates/wallet/access_denied.html
<!DOCTYPE html>
<html>
<head>
    <title>Access Denied</title>
</head>
<body>
    <div class="alert alert-danger">
        <strong>Access Denied:</strong> You do not have permission to access this page.
    </div>
</body>
</html>

wallet/templates/wallet/userbase.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Wallet</title>
    <link
      href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet" />
    <link href="{% static 'css/styleBASE.css' %}" rel="stylesheet" />

    <link rel="shortcut icon" href="{% static 'img/title.png' %}" />
    <link
      rel="stylesheet"
      href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Poppins"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>

    <script
      defer
      src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
      integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
      crossorigin="anonymous"
    ></script>
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
      integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
      crossorigin="anonymous"
    ></script>
    {% block headerinclude %} {% endblock %}
    <!-- Style -->
    <style>

    /* CSS for active and hover states */
    .list-group-item {
        /* Define the default styles for the list items */
        background-color: #ffffff;
        color: #000000;
    }

    .list-group-item:hover {
        /* Define styles for hover state */
        background-color: #f0f0f0;
        color: #000000;
    }

    .list-group-item.active-link {
        /* Define styles for active state */
        background-color: #007bff;
        color: #ffffff;
    }


      .main-scroll-div {
        width: 90%;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: space-between;
        /* border: 2px solid #000000; */
      }
      .cover {
        position: relative;
        width: 90%;
        height: 50%;
      }
      .cover::before {
        position: absolute;
        content: "";
        left: 0;
        top: 0;
        z-index: 99;
        height: 100%;
        width: 150px;
        background-image: linear-gradient(90deg, black, transparent);
      }

      .cover::after {
        position: absolute;
        content: "";
        right: 0;
        top: 0;
        z-index: 99;
        height: 100%;
        width: 150px;
        background-image: linear-gradient(-90deg, black, transparent);
      }
      .scroll-images {
        width: 100;
        height: auto;
        display: flex;
        justify-content: left;
        align-items: center;
        overflow: auto;
        position: relative;
        scroll-behavior: smooth;
      }

      .child {
        min-width: 600px;
        height: 450px;
        margin: 1px 10px;
        cursor: pointer;
        border: 1px solid #ffffff;
        overflow: hidden;
      }
      .scroll-images::-webkit-scrollbar {
        -webkit-appearance: none;
      }

      .child-img {
        width: 100%;
        height: 100%;
      }

      .settings-button {
        color: #000;
        margin-left: 10px; /* Adjust the margin as needed */
        font-size: 24px;
        padding: 15px 20px;
      }

      .header-wrapper {
        position: fixed;
        width: 100%;
        z-index: 1000;
      }

      header {
        padding: 25px 20px;
        background-color: #faca00;
      }

      header img {
        margin-right: 10px;
      }

      .navbar-toggler {
        color: #f8f9fa; /* Set the text color */
        background-color: #9c7b16; /* Set the background color */
        border-color: #ffff; /* Set the border color */
      }
      .bg-custom-color {
        background-color: #faca04;
        max-height: 100px;
        /* Add any additional styles you want */
      }

      .active-link {
        color: #9c7b16; /* Change this color to your desired active link color */
      }

      /* Add styles for links */
      .sidebar-link {
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 10px 20px;
        margin-bottom: 10px;
        border-radius: 5px;
        transition: background-color 0.3s ease;
      }

      .sidebar-wrapper {
        background-color: #000000; /* Change sidebar background color */
      }

      h2 {
        color: #ffffff;
      }

      .list-group-item.active-link {
        color: #faca00;
      }
      /* Add spacing between links */
      .list-group-item:not(:valid) {
        margin-left: 5px;
        margin-bottom: 10px;
        max-width: 95%;
        border-radius: 15px 5px;
        background-color: #333333;
        color: #ffffff;
        text-align: center;
        font-family: "Poppins";
      }

      .All-Font {
        font-family: "Poppins";
      }
    </style>
  </head>

  <body>
    <div id="header-wrapper">
      <!-- Header with Logo -->
      <header class="bg-custom-color">
        <div class="container-fluid">
          <div class="row">
            <div class="col-2">
              <!-- Logo  -->
              <img
                src="{% static 'img/w3.png' %}"
                alt="Logo"
                width="200"
                height="60"
              />
            </div>

            <div class="col-10 d-flex justify-content-end align-items-center">
              <div>
                <div class="card" style="padding:10px 10px 3px 10px; filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25)); background-color:#faca04">
                <h5 class="All-Font" style="color: #000">
                  <!-- <img src="{% static 'img/user.png' %}"  width="40" height="40" style="border-radius: 50%;"> -->
                  {{email}}
                </h5>
              </div>
            </div>

            <div
              class="col-2 d-flex flex-column justify-content-end align-items-center"
              style="margin-top: -10px"
            >
              <!-- Points Icon -->
              <div class="text-center">
                <img
                  src="{% static 'img/point.png' %}"
                  width="30"
                  height="30"
                  alt="Points Icon"
                />
                <span>{{ point_balance }}</span>
              </div>
              <!-- Coins Icon -->
              <div class="text-center mt-3">
                <img
                  src="{% static 'img/coin.png' %}"
                  width="30"
                  height="30"
                  alt="Coins Icon"
                />
                <span>{{ coin_balance }}</span>
              </div>
            </div>
          </div>
        </div>
      </header>
    </div>
    <div class="d-flex" id="wrapper">
      <!-- Sidebar -->
      <div class="sidebar-wrapper border-right" id="sidebar-wrapper">
        <div class="sidebar-heading text-center">
          <h2 class="All-Font">
            WALLET
            <!-- <img src="{% static 'img/wallet.png' %}" alt="wallet"> -->
          </h2>
        </div>
        <div class="list-group list-group-flush">
          {% if user.is_authenticated %}
          <a
            href="{% url 'wallet:usrdashboard' %}"
            class="list-group-item list-group-item-action All-Font {% if 'usrdashboard' in request.path %}active-link{% endif %}"
            >DASHBOARD</a
          >
          <a
            href="{% url 'wallet:create-coin-transaction' %}"
            class="list-group-item list-group-item-action All-Font {% if 'createCoin' in request.path %}active-link{% endif %}"
            >COINS</a
          >
          <a
            href="{% url 'wallet:pointsdash' %}"
            class="list-group-item list-group-item-action All-Font {% if 'pdash' in request.path %}active-link{% endif %}"
            >POINTS</a
          >
          <!-- <a href="{% url 'wallet:settings' %}" class="list-group-item list-group-item-action {% if 'settings' in request.path %}active-link{% endif %}">Settings
                    <img src="{% static 'img/angle-small-down.png' %}" class="icon-right" alt="Icon" style="width: 16px; height: 16px;">   
                    </a> -->
          {% if request.user.is_staff %}
          <a
            href="{% url 'wallet:teacheruserlist' %}"
            class="list-group-item list-group-item-action All-Font {% if 'teacher_user_list' in request.path %}active-link{% endif %}"
            >TEACHER TAB</a
          >
          {% endif %}
          <a
            href="#"
            class="list-group-item list-group-item-action All-Font {% if 'settings' in request.path or 'edit_profile' in request.path %}active-link{% endif %}"
            id="settings-button"
            >SETTINGS
            <img
              src="{% static 'img/angle-small-down.png' %}"
              class="icon-right"
              alt="Icon"
              style="width: 16px; height: 16px"
            />
          </a>

          <div id="settings-dropdown" style="display: none">
            <!-- Content of your dropdown menu -->
            <ul>
              <li>
                <a
                  href="{% url 'wallet:settings' %}"
                  class="list-group-item list-group-item-action {% if 'settings' in request.path %}active-link{% endif %}"
                >
                  CHANGE PASSWORD</a
                >
              </li>
              <li>
                <a
                  href="{% url 'wallet:edit_profile' %}"
                  class="list-group-item list-group-item-action {% if 'settings' in request.path %}active-link{% endif %}"
                >
                  EDIT PROFILE</a
                >
              </li>
              <!-- Add more dropdown options here -->
            </ul>
          </div>

          <a
            href="{% url 'wallet:logout' %}"
            class="list-group-item list-group-item-action sidebar-link {% if 'logout' in request.path %}active-link{% endif %}"
            style="
              display: block;
              width: 100%;
              text-align: center;
              margin-top: 75%;
            "
            >LOGOUT</a
          >

          {% else %}
          <a
            href="/wallet/user_login/"
            class="list-group-item list-group-item-action sidebar-link"
            onmouseover="this.style.backgroundColor='#333333'"
            onmouseenter="this.insertAdjacentHTML('beforebegin', '<span class=\'highlight-box\'></span>')"
            onmouseleave="this.previousSibling.remove()"
          >
            Login !
          </a>
          <a
            href="{% url 'wallet:register' %}"
            class="list-group-item list-group-item-action sidebar-link {% if 'register' in request.path %}active-link{% endif %}"
            >Register</a
          >
          {% endif %}
        </div>
      </div>
      <!-- /#sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper" , style="background-color: #f8f9fa">
        <div class="container-fluid">{% block body_block %} {% endblock %}</div>
      </div>
      <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Custom scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>
      $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>
    <script>
      // JavaScript to toggle the visibility of the dropdown
      document
        .getElementById("settings-button")
        .addEventListener("click", function () {
          var dropdown = document.getElementById("settings-dropdown");
          if (
            dropdown.style.display === "none" ||
            dropdown.style.display === ""
          ) {
            dropdown.style.display = "block";
          } else {
            dropdown.style.display = "none";
          }
        });

      // Close the dropdown if the user clicks outside of it
      window.addEventListener("click", function (event) {
        var dropdown = document.getElementById("settings-dropdown");
        var button = document.getElementById("settings-button");
        if (
          event.target !== button &&
          !button.contains(event.target) &&
          event.target !== dropdown &&
          !dropdown.contains(event.target)
        ) {
          dropdown.style.display = "none";
        }
      });
    </script>
  </body>
</html>