WILMS/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import ReactAppView
from wallet import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from .views import serve_manifest


from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('wallet/', include('wallet.urls', namespace='wallet')),  # Include app-specific URLs with the 'wallet' namespace
    path('walletAPI/', include(('walletAPI.urls', 'walletAPI'), namespace='walletAPI')),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('wiladmin/', include('wiladmin.urls')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('' , views.IndexView.as_view(), name='index'),
    path('facility/', include('facility.urls')),

    re_path(r'^manifest\.json$', serve_manifest),
    
    
    
    path('logout/',views.UserLogoutView.as_view(),name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='wallet/password_reset.html'), name="password_reset"),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='wallet/password_reset_done.html'), name = "password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='wallet/password_reset_confirm.html'), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='wallet/password_reset_complete.html'), name='password_reset_complete'),

# for api front end
    path('booking/login/', ReactAppView.as_view(), name='login'),
    # path('', ReactAppView.as_view(), name='login'),  # Uncomment this line if you want / to point to the login page
    path('booking/tracker/', ReactAppView.as_view(), name='tracker'),
    path('booking/calendar/', ReactAppView.as_view(), name='calendar'),
    path('booking/logs/', ReactAppView.as_view(), name='attendance_logs'),
    path('booking/bookings/', ReactAppView.as_view(), name='my_reservations'),
    path('attendance/', ReactAppView.as_view(), name='attendance'),
    path('booking/attendance/', ReactAppView.as_view(), name='booking_attendance'),
    path('react/', ReactAppView.as_view(), name='react_app'),


    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from .views import *
from api.controllers.calendarController import CalendarController
from api.controllers.bookingController import BookingController
from api.controllers.detailsController import DetailsController
from api.controllers.managementController import ManagementController
from api.controllers.dashboardController import DashboardController
from api.controllers.logsController import *
from api.controllers.tapController import TapController
from api.controllers.logsController import LogsController
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
urlpatterns = [
    # path('booking/',BookingDetail.as_view(),name='creation'),
    # path('currentBookings/',CurrentBookings.as_view(),name='currentBookings'),
    # path('getBookingByVenue/<id>/',BookingByVenue.as_view(),name='bookingsByVenue'),
    # path('booking/',BookingDetail.as_view(),name='creation'),

    ##Calendar controllers
    path('createBooking/',CalendarController.saveBooking,name='create booking'),
    path('currentBookings/',CalendarController.getCurrentBookings,name='current bookings'),
    path('getEvents/', CalendarController.getEvents, name='get events'),
    ##Controllers na wa pa na separate
    path('getAttendees/<id>/',AttendeeDetail.as_view(),name='getBookingAttendees'),
    path('users/',Users.as_view(),name='getAllUsers'),

    #view details na controller
    path('cancelBooking/<id>',DetailsController.cancelBooking,name="cancelbooking"),

    #booking creation controller
    path('calculateCost/<venue_id>',BookingController.calculateCost,name="calculate payment or cost"),
    path('getUsers/',BookingController.getAllUsers,name="get all users"),

    #booking management controller
    #admin view sa booking management
    path('getDurations/',BookingController.getDurations,name="calculate total hour for users"),
    path('getAllBookings/',ManagementController.getAllBooking,name="get all bookings"),
    path('getAllCancelledBookings/',ManagementController.getAllCancelledBooking,name="get all cancelled bookings"),
    path('getAllNoShowBookings/',ManagementController.getAllNoShowBooking,name="get all no show bookings"),
    #for non admin or normal users  
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('getAllUserBookings/<user_id>/',ManagementController.getAllUserBookings,name="get booking of user"),
    path('getUpcomingUserBookings/<user_id>/',ManagementController.getUpcomingUserBookings,name="get upcoming bookings of user"),
    path('getHistoryUserBookings/<user_id>/',ManagementController.getHistoryUserBookings,name="get user bookings in the past"),
    #for editting
    path('deleteAttendee/<attendee_id>/',ManagementController.removeBookingAttendee,name="remove attendee"),
    path('addAttendee/<booking_id>/',ManagementController.addBookingAttendee,name="add attendee for booking"),
    path('editBooking/<booking_id>/',ManagementController.editBooking,name="update booking details"),
    #for tap or sign in
    path('logAttendance/',TapController.logAttendance,name="tapping or sign in"),
    #for dashboard
    path('getSignedIn/',DashboardController.getSignedIn,name='get all signed in currently in facilities'),
    path('getExpected/',DashboardController.getExpected,name="get all expected count for each facility"),
    path('getWaiting/',DashboardController.getWaiting,name="get all waiting for bookings"),
    path('getOngoing/',DashboardController.getOngoing,name="get all ongoing"),
    path('getOverstaying/',DashboardController.getOverstaying,name="get overstaying beyond their booking"),
    path('login/',login,name='login'),
    path('signup/',signup,name='signup'),
    #for logs page
    path('getAllAttendance/',LogsController.getAllAttendance, name="get all attendance"),



    # kirk added

    path('react/', ReactAppView.as_view(), name='react_app'),
]

facility/urls.py
# from FacilityManagement.facility import facility
from . import views
from django.urls import path
# from .views import put
app_name ='facility'

urlpatterns =[
    path('get-facility/', views.get_facility, name='get_facility'),
    path('facilitymanagement', views.display_facility, name='facility'),
    path('facilitymanagement/updatefaci', views.display_facility, name='updatefaci'),
    path('rules', views.rules_facility, name='rules'),
    path('facilitymanagement/deleteFacility/<int:id>', views.delete_facility, name='deleteFacility'),
    path('facilitymanagement/restoreFacility/<int:id>', views.restoreFacility, name='restoreFacility'),
    path('facilitymanagement/updateFacility/<int:id>', views.update_facility, name='updatefacility'),
    path('facilitymanagement/frules/facilitytable', views.displayall_setting_facility, name='facilitytable'), 

    # path('sessfaci/<int:id>', views.set_session_facility, name='sessfaci'),
# facilitymainrules_back
    path('facilitymanagement/frules/facimainback', views.facilitymainrules_back, name='facimainback'),
    
    path('facilitymanagement/frules/facilityRules/<int:id>', views.display_facility_mainrules, name='facilityRules'),
    path('facilitymanagement/frules/facilitydelfmrules/<int:id>', views.delete_facilitymainrules, name='delfmrules'),    
    path('facilitymanagement/frules/facilitysetfmstatus/<int:id>', views.facilitymainrules_set, name='setfmstatus'),
    path('facilitymanagement/frules/facilitydelfmstatus/<int:id>', views.delete_setfacilitymainrules_status, name='delfmstatus'),
    path('facilitymanagement/frules/facilitydelfprules/<int:id>', views.delete_facilitypromorules, name='delfprules'), 
    path('facilitymanagement/frules/facilitydelfsrules/<int:id>', views.delete_facilitysubrules, name='delfsrules'), 



# status to 1
    path('facilitymanagement/frules/facilitysetfmstatus_one/', views.is_setfacilitymainrules_status, name='setfmstatus_one'),
    # path('userMainRules/<int:id>', views.display_user_mainrules, name='userMainRules'),
    path('user', views.user_create, name='user'),
    
    path('rulessummary/<int:id>', views.restoreFacility, name='restoreFacility'),
    path('rulessummary', views.display_setting_facility, name='rulessummary'),
    path('facilitymanagement/frules/updatesettingfacility/<int:id>', views.update_setting_facility, name='settingfacility'),

    path('facilitymanagement/frules/facilitySubrules/<int:id>', views.display_facility_subrules, name='facilitysubrules'),
    path('facilitymanagement/frules/facilitysetfsstatus_one/', views.is_setfacilitysubrules_status, name='setfsstatus_one'),
    path('facilitymanagement/frules/facilitysetfsstatus/<int:id>', views.facilitysubrules_set, name='setfsstatus'),
    path('facilitymanagement/frules/facilitydelfsstatus/<int:id>', views.delete_setfacilitysubrules_status, name='delfsstatus'),

    path('facilitymanagement/frules/facilityPromrules/<int:id>', views.display_facility_promorules, name='facilitypromorules'),
    path('facilitymanagement/frules/facilitysetfpstatus_one/', views.is_setfacilitypromorules_status, name='setfpstatus_one'),
    path('facilitymanagement/frules/facilitysetfpstatus/<int:id>', views.facilitypromorules_set, name='setfpstatus'),
    path('facilitymanagement/frules/facilitydelfpstatus/<int:id>', views.delete_setfacilitypromorules_status, name='delfpstatus'),

    path('facilitymanagement/calendar', views.display_calendar, name='calendar'),
    path('delevent/<int:id>', views.delete_event, name='delevent'),
    
    path('facilitymanagement/calendar/calendarview', views.display_calendarview, name='calendarview'),
    
    path('revenue/revenuedashboard', views.revenue_dashboard, name='revenuedashboard'),
    path('revenue/revenuereport', views.revenue_report, name='revenuereport'),
    # path('revenue_dis', views.revenue_dashboard_copy, name='revenue_dis'),
# 
    path('get_events/', views.get_events, name='get_events'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),


# user type mainrules urls
    path('facilitymanagement/urules/updateUmainrules/<int:id>', views.update_userMainRules, name='updateumainrules'),
    path('facilitymanagement/urules/usertable', views.displayall_setting_usertype, name='usertable'), 
    path('facilitymanagement/urules/delumrules/<int:id>', views.delete_usermainrules, name='delumrules'),    
    path('facilitymanagement/urules/setumstatus/<int:id>', views.usertypemainrules_set, name='setumstatus'),
    path('facilitymanagement/urules/delumstatus/<int:id>', views.delete_setusermainrules_status, name='delumstatus'),
    path('facilitymanagement/urules/setumstatus_one/', views.is_setusermainrules_status, name='setumstatus_one'),
    path('facilitymanagement/urules/userRules/<int:id>', views.display_usertype_mainrules, name='userRules'),
# user type subrules url
    path('facilitymanagement/urules/updateUsubrules/<int:id>', views.update_userSubRules, name='updateusubrules'),
    path('facilitymanagement/urules/delusrules/<int:id>', views.delete_usersubrules, name='delusrules'),    
    path('facilitymanagement/urules/setusstatus/<int:id>', views.usertypesubrules_set, name='setusstatus'),
    path('facilitymanagement/urules/delusstatus/<int:id>', views.delete_setusersubrules_status, name='delusstatus'),
    path('facilitymanagement/urules/setusstatus_one/', views.is_setusersubrules_status, name='setusstatus_one'),
    path('facilitymanagement/urules/userSubRules/<int:id>', views.display_usertype_subrules, name='userSubRules'),

    path('facilitymanagement/urules/updateUpromorules/<int:id>', views.update_userPromoRules, name='updateupromorules'),
    path('facilitymanagement/urules/deluprules/<int:id>', views.delete_userpromorules, name='deluprules'),    
    path('facilitymanagement/urules/setupstatus/<int:id>', views.usertypepromorules_set, name='setupstatus'),
    path('facilitymanagement/urules/delupstatus/<int:id>', views.delete_setuserpromorules_status, name='delupstatus'),
    path('facilitymanagement/urules/setupstatus_one/', views.is_setuserpromorules_status, name='setupstatus_one'),
    path('facilitymanagement/urules/userPromoRules/<int:id>', views.display_usertype_promorules, name='userPromoRules'),

    path('facilitymanagement/urules/umainback', views.usertypemainrules_back, name='umainback'),
]

wallet/urls.py
from django.urls import path
from wallet.views import AccountStatusView, GetUserStatusView, IndexView, RegisterView, UserLoginView, DashboardView, UserListView,UserLogoutView,UserDashboardView,PointsDashboardView, TransactionApprovalView,SuccessRedirectView,CoinTransactionCreateAndDashboardView,GetTransactionDetailsView,SettingsView,ChangePasswordView, UpdateAccountTypeView, TeacherUserListView, AdminAwardPointsToTeacherView, ActivateAccountView,ScanAndDisplayRFIDView,EditUserProfileView
# Increment 2
from django.conf import settings
from django.conf.urls.static import static  

from django.contrib.auth import views as auth_views

from . import views

app_name = 'wallet'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),  
    path('user_list/', UserListView.as_view(), name='userlist'),
    # path('store_transaction/', StoreTransactionView.as_view(), name='store_transaction'),
    path('logout/',UserLogoutView.as_view(),name='logout'),
    path('usrdashboard/', UserDashboardView.as_view(), name='usrdashboard'), 
    path('pdash/',PointsDashboardView.as_view(),name='pointsdash'),
    # INCREMENT 2
    path('createCoin/', CoinTransactionCreateAndDashboardView.as_view(), name='create-coin-transaction'),
    
    path('request/approval/', TransactionApprovalView.as_view(), name='request-approval'),
    path('success/',SuccessRedirectView.as_view(),name='success'),

    path('request/approval/approve-transaction/', views.approve_transaction, name='approve-transaction'),
    path('request/approval/deny-transaction/', views.deny_transaction, name='deny-transaction'),
    path('request/approval/get-transaction-details/', GetTransactionDetailsView.as_view(), name='get_transaction_details'),

    # INCREMENT 3
    path('settings/',SettingsView.as_view(),name='settings'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),

    # INCREMENT 4
    path('update_account_type/<int:id>/', UpdateAccountTypeView.as_view(), name='update_account_type'),
    path('teacher_user_list/', TeacherUserListView.as_view(), name='teacheruserlist'),

    # BONUS CONTENT
    path('award_points_to_teacher/', views.AdminAwardPointsToTeacherView.as_view(), name='award_points_to_teacher'),


    # RFID
    path('activate_account/', ActivateAccountView.as_view(), name='activate_account'),

    # GRAB VALUES
    path('scan/', ScanAndDisplayRFIDView.as_view(), name='scan'),

    # EDIT PROFILE
    path('edit_profile/', EditUserProfileView.as_view(), name='edit_profile'),

    #ACCOUNT Status
    path('account_status/<int:user_id>/', AccountStatusView.as_view(), name='account_status'),
    path('get_user_status/<int:user_id>/', GetUserStatusView.as_view(), name='get_user_status'),

  





    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiladmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AdminLoginController.as_view(), name='index'),
    path('login', views.AdminLoginController.as_view(), name='adminlogin'),
    path('logout', views.handleLogout, name='adminlogout'),
    path('admindashboard', views.AdminDashboardController.as_view(), name='admindashboard'),
    path('updatedashboard', views.AdminDashboardController.update_dashboard, name='updatedashboard'),
    path('reportlogs', views.AdminReportLogsController.as_view(), name='reportlogs'),
    path('todayreportlogs', views.AdminReportLogsController.getTodayReportLogs, name='todaylogs'),
    path('walkindashboard', views.AdminWalkinDashboardController.as_view(), name='walkindashboard'),
    path('reserveddashboard', views.AdminReservedDashboardController.as_view(), name='reserveddashboard'),
    path('updatebooking/<int:bookingid>', views.AdminWalkinDashboardController.as_view(), name='updatebooking'),
    path('deletebooking/<int:bookingid>', views.AdminWalkinDashboardController.as_view(), name='deletebooking'),
    path('updatereserved/<int:id>', views.AdminReservedDashboardController.as_view(), name='updatereserved'),
    path('deletereserved/<int:id>', views.AdminReservedDashboardController.as_view(), name='deletereserved'),
    path('bookguest', views.BookGuestController.as_view(), name='bookguest'),
    path('workspaces', views.ViewWorkspacesController.as_view(), name='workspaces'),
    path('workspaces/<str:areaid>', views.ViewWorkspacesController.as_view(), name='usersinarea'),
    path('updateworkspaces', views.ViewWorkspacesController.update_workspaces, name='updateworkspaces'),
    path('test', views.TestController.as_view(), name='test'),
    path('test/<str:areaid>', views.TestController.as_view(), name='testusers'),
]

wiladmin/templates/wiladmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>WILMS | Crowd Control</title>
    <link href="{% static 'icon/favicon3.ico' %}" rel="shortcut icon">
    <link href="{% static 'facility/extended.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/extend-base.css' %}" /> 
    <link
      href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet" />
    <link href="{% static 'css/baseStyle.css' %}" rel="stylesheet" />
    <link href="{% static 'css/base.css' %}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
<style>    
    button#koisk {
  opacity: 1;
  z-index: 999999;
  transform: translateX(-100%);
  transition: opacity 0.3s ease, transform 0.3s ease;
  margin-left:25%; 
  font-size: 16px;   
            position: fixed;
            color: rgb(232, 214, 214);
            background: #ffcc0137;
            filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
            justify-content: left;
            width: max-content;
            margin-top: 40%;
            height: max-content;
             /* Initial position outside the viewport */
            align-items: center;
            padding: 20px; 
            border-radius: 15px;
}
button#koisk:hover{
  background: #ffcc01;
  animation: slideFromRight 0.5s ease forwards;
}
@keyframes slideFromRight {
  0% {
    opacity: 0;
    transform: translateX(-100%);
  }
  100% {
    opacity: 1;
    transform: translateX(0);
    margin-left: -17vw; /* New left position after entering */
  }
}

@keyframes slideExitRight {
  0% {
    opacity: 1;
    transform: translateX(0);
    margin-left: 1vw; /* Keep consistent with the final position in slideFromLeft */
  }
  100% {
    opacity: 0;
    transform: translateX(-100%);
    margin-left: -200px; /* Return to the initial position outside the viewport */
  }
}
</style>
    {% block headerinclude %} {% endblock %}
  </head>
  <body>
    <div class="d-flex" id="wrapper">
      <div class="sidebar-wrapper border-right" id="sidebar-wrapper" style="  overflow: hidden;
      height: 100%;
      width:16.3%;
      position: fixed;
      top: 100px;">
        <div class="avatar">
          {% block pic %}
          <img src="{% static 'media/admin3.png' %}" alt="Another Profile Picture">
          {% endblock %}
        </div>
        <li style="list-style: none; color: white; text-align: center; padding: 0rem; margin-bottom: 10px;">{{ firstname }}</li> 
        <div class="list-group list-group-flush">
          {% if user.is_authenticated %}
          <a
            href="admindashboard"
            class="list-group-item list-group-item-action {% if 'admindashboard' in request.path %}active-link{% endif %}"
            >Dashboard</a
          >
          <a
            href="walkindashboard"
            class="list-group-item list-group-item-action {% if 'walkindashboard' in request.path %}active-link{% endif %}"
            >Walk-in Dashboard</a
          >
          <a
            href="reserveddashboard"
            class="list-group-item list-group-item-action {% if 'reserveddashboard' in request.path %}active-link{% endif %}"
            >Reserved Dashboard</a
          >
          <a
            href="workspaces"
            class="list-group-item list-group-item-action {% if 'workspaces' in request.path %}active-link
                                                          {% elif 'A1' in request.path %}active-link
                                                          {% elif 'A2' in request.path %}active-link
                                                          {% elif 'A3' in request.path %}active-link
                                                          {% elif 'A4' in request.path %}active-link
                                                          {% elif 'A5' in request.path %}active-link
                                                          {% elif 'A6' in request.path %}active-link
                                                          {% elif 'A7' in request.path %}active-link
                                                          {% elif 'A8' in request.path %}active-link
                                                          {% elif 'A9' in request.path %}active-link
                                                          {% endif %}"
            >View Workspaces</a
          >

          <a
            href="bookguest"
            class="list-group-item list-group-item-action {% if 'bookguest' in request.path %}active-link{% endif %}"
            >Book Guest</a
          >

          <a
            href="reportlogs"
            class="list-group-item list-group-item-action {% if 'reportlogs' in request.path %}active-link{% endif %}"
            >Report Logs</a
          >

          <div style="margin-bottom: 280px"></div>

          {% else %}
          <a
            href="/wallet/user_login/"
            class="list-group-item list-group-item-action sidebar-link"
            onmouseover="this.style.backgroundColor='#f5f5f5'"
            onmouseenter="this.insertAdjacentHTML('beforebegin', '<span class=\'highlight-box\'></span>')"
            onmouseleave="this.previousSibling.remove()"
          >
            Login
          </a>
          <a
            href="{% url 'wallet:register' %}"
            class="list-group-item list-group-item-action sidebar-link {% if 'register' in request.path %}active-link{% endif %}"
            >Register</a
          >
          {% endif %}
        </div>
      </div>

      {% block body_block %} {% endblock %}
    </div>
    <nav class="horizontal">
      <ul class="left">
        <li><a href="{% url 'wallet:index' %}"><img src="{% static 'media/WILMS.png' %}" alt="Home"></a></li>
      </ul>
      <ul class="center" >
        <div>
          <<button id="koisk" style="left: 100%; width: 30vw; text-align: left;"><a style="font-weight: 800; font-size: 21px;" href="{% url 'wallet:activate_account' %}">😺 ACTIVATION KOISK</a></button></div>   
        {% if messages %}
        {% for message in messages %}
         
            {% if message.tags == 'success' %}
            <div>
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  <h4 style="margin:1px; font-size: 16px;">✅ Success!</h4>{{ message }}</div>
            {% elif message.tags == 'warning' %}
            <div>
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                <h4 style="margin:1px; font-size: 16px;">⚠️ Warning!</h4>{{ message }}</div>
            {% elif message.tags == 'error' %}
            <div>
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  <h4 style="margin:1px; font-size: 16px;">⛔ Oops!</h4>{{ message }}</div>
            {% endif %} 
          {% endfor %}
          {% endif %}
    
    </ul>
      <ul class="right">
        <button class="adminlabel" style="left:46%;"><a class="menugroup menugroup-action {% if 'home' in request.path %}active-link{% endif %}" href="{% url 'wallet:index' %}">HOME</a></button>
        <button class="adminlabel" style="left:52%;"><a class="menugroup menugroup-action {% if 'facility' in request.path %}active-link{% endif %}" href="{% url 'facility:facility' %}">FACILITY</a></button>
        <button class="adminlabel" style="left:60%; border: 0px;"><a class="menugroup menugroup-action {% if 'booking' in request.path %}active-link{% endif %}" href="#">BOOKING</a></button>
        <button class="adminlabel" style="left:68%;"><a class="menugroup menugroup-action {% if 'wallet' in request.path %}active-link{% endif %}" href="{% url 'wallet:dashboard' %}">WALLET</a></button>
        <button class="adminlabel" style="left:75%;"><a class="menugroup menugroup-action {% if 'wiladmin' in request.path %}active-link{% endif %}" href="{% url 'admindashboard' %}">CROWD CONTROL</a></button>
        <button class="adminlabel" style="width: fit-content;left:90%;" ><a class="menugroup" style=" color: red;" href="{% url 'wallet:logout' %}">LOGOUT</a></button>
      </ul>
      
    </nav> 

    <script>
      function closeOverlay() {
          document.getElementById('overlay').style.display = 'none';
      }
  </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Custom scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>
      $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>

    <!-- Bootstrap core JavaScript -->
    <!-- Font Awesome JS -->
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
      integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
      crossorigin="anonymous"
    ></script>
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
      integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"
      integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'functions-js/search.js' %}"></script>
  </body>
</html>

wiladmin/templates/wiladmin/bookguest.html
{% extends 'wiladmin/base.html' %} {% load static %} {% block body_block %}

<link rel="stylesheet" href="{% static 'css/bookguest.css' %}" />
<body>
  <div class="table" style="background: transparent">
    <div class="content-container">
      <div class="buttonContainer">
        <form method="POST">
          {% csrf_token %}
          <input
            type="text"
            class="username"
            placeholder="Enter Name or ID Number"
            name="userid"
          /><br /><br />
          <label for="areas">Select an area:</label>
          {{ form.area }}
          </select>
          <br><br>
          <input type="submit" class="button" value="BOOK" />
        </form>
      </div>
    </div>
  </div>
</body>
{% endblock %}