WILMS/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import ReactAppView
from wallet import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from .views import serve_manifest


from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('wallet/', include('wallet.urls', namespace='wallet')),  # Include app-specific URLs with the 'wallet' namespace
    path('walletAPI/', include(('walletAPI.urls', 'walletAPI'), namespace='walletAPI')),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('wiladmin/', include('wiladmin.urls')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('' , views.IndexView.as_view(), name='index'),
    path('facility/', include('facility.urls')),

    re_path(r'^manifest\.json$', serve_manifest),
    
    
    
    path('logout/',views.UserLogoutView.as_view(),name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='wallet/password_reset.html'), name="password_reset"),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='wallet/password_reset_done.html'), name = "password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='wallet/password_reset_confirm.html'), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='wallet/password_reset_complete.html'), name='password_reset_complete'),

# for api front end
    path('booking/login/', ReactAppView.as_view(), name='login'),
    # path('', ReactAppView.as_view(), name='login'),  # Uncomment this line if you want / to point to the login page
    path('booking/tracker/', ReactAppView.as_view(), name='tracker'),
    path('booking/calendar/', ReactAppView.as_view(), name='calendar'),
    path('booking/logs/', ReactAppView.as_view(), name='attendance_logs'),
    path('booking/bookings/', ReactAppView.as_view(), name='my_reservations'),
    path('attendance/', ReactAppView.as_view(), name='attendance'),
    path('booking/attendance/', ReactAppView.as_view(), name='booking_attendance'),
    path('react/', ReactAppView.as_view(), name='react_app'),


    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from .views import *
from api.controllers.calendarController import CalendarController
from api.controllers.bookingController import BookingController
from api.controllers.detailsController import DetailsController
from api.controllers.managementController import ManagementController
from api.controllers.dashboardController import DashboardController
from api.controllers.logsController import *
from api.controllers.tapController import TapController
from api.controllers.logsController import LogsController
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
urlpatterns = [
    # path('booking/',BookingDetail.as_view(),name='creation'),
    # path('currentBookings/',CurrentBookings.as_view(),name='currentBookings'),
    # path('getBookingByVenue/<id>/',BookingByVenue.as_view(),name='bookingsByVenue'),
    # path('booking/',BookingDetail.as_view(),name='creation'),

    ##Calendar controllers
    path('createBooking/',CalendarController.saveBooking,name='create booking'),
    path('currentBookings/',CalendarController.getCurrentBookings,name='current bookings'),
    path('getEvents/', CalendarController.getEvents, name='get events'),
    ##Controllers na wa pa na separate
    path('getAttendees/<id>/',AttendeeDetail.as_view(),name='getBookingAttendees'),
    path('users/',Users.as_view(),name='getAllUsers'),

    #view details na controller
    path('cancelBooking/<id>',DetailsController.cancelBooking,name="cancelbooking"),

    #booking creation controller
    path('calculateCost/<venue_id>',BookingController.calculateCost,name="calculate payment or cost"),
    path('getUsers/',BookingController.getAllUsers,name="get all users"),

    #booking management controller
    #admin view sa booking management
    path('getDurations/',BookingController.getDurations,name="calculate total hour for users"),
    path('getAllBookings/',ManagementController.getAllBooking,name="get all bookings"),
    path('getAllCancelledBookings/',ManagementController.getAllCancelledBooking,name="get all cancelled bookings"),
    path('getAllNoShowBookings/',ManagementController.getAllNoShowBooking,name="get all no show bookings"),
    #for non admin or normal users  
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('getAllUserBookings/<user_id>/',ManagementController.getAllUserBookings,name="get booking of user"),
    path('getUpcomingUserBookings/<user_id>/',ManagementController.getUpcomingUserBookings,name="get upcoming bookings of user"),
    path('getHistoryUserBookings/<user_id>/',ManagementController.getHistoryUserBookings,name="get user bookings in the past"),
    #for editting
    path('deleteAttendee/<attendee_id>/',ManagementController.removeBookingAttendee,name="remove attendee"),
    path('addAttendee/<booking_id>/',ManagementController.addBookingAttendee,name="add attendee for booking"),
    path('editBooking/<booking_id>/',ManagementController.editBooking,name="update booking details"),
    #for tap or sign in
    path('logAttendance/',TapController.logAttendance,name="tapping or sign in"),
    #for dashboard
    path('getSignedIn/',DashboardController.getSignedIn,name='get all signed in currently in facilities'),
    path('getExpected/',DashboardController.getExpected,name="get all expected count for each facility"),
    path('getWaiting/',DashboardController.getWaiting,name="get all waiting for bookings"),
    path('getOngoing/',DashboardController.getOngoing,name="get all ongoing"),
    path('getOverstaying/',DashboardController.getOverstaying,name="get overstaying beyond their booking"),
    path('login/',login,name='login'),
    path('signup/',signup,name='signup'),
    #for logs page
    path('getAllAttendance/',LogsController.getAllAttendance, name="get all attendance"),



    # kirk added

    path('react/', ReactAppView.as_view(), name='react_app'),
]

walletAPI/urls.py
from django import views
from django.urls import path
from walletAPI.views import login_view, CreateVendorTransactionView,TransactionReceiptView,logout_view, CustomLoginAPIView

app_name = 'walletAPI'

urlpatterns = [
    path('', login_view, name='login'),
    path('login/', login_view, name='login'),
    # Define other URL patterns for your API views
    path('create-transaction/', CreateVendorTransactionView.as_view(), name='create-transaction'),
    path('receipt/', TransactionReceiptView.as_view(), name='transaction_receipt'),
    path('logout/', logout_view, name='logout'),
    path('customlogin/',CustomLoginAPIView.as_view(), name='custom_login_api'),
]

api/models/BookingModel.py
import uuid
from django.db import models
# from django.core.validators import MaxValueValidator, MinValueValidator
# from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from WILMS import settings
from api.models.VenueModel import Venue
from facility.models import Facility
from django.db import models


class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    bookDate=models.DateTimeField( auto_now_add=True)
    date=models.DateField(null=True)
    startTime=models.TimeField(null=True)
    endTime=models.TimeField(null=True)
    purpose=models.CharField( max_length=50,default='Studying',)
    coins=models.FloatField(default=0)
    points=models.FloatField(default=0)
    computers=models.IntegerField(default=0)
    description=models.CharField(max_length=100,null=True)
    isUsed= models.BooleanField(default=False, null=True)
    duration=models.FloatField(default=0)
    referenceNo=models.TextField(max_length=8,blank=True,unique=True, default=uuid.uuid1)
    officeName=models.CharField(max_length=50,null=True)
    status=models.CharField(max_length=20,null=True, default='Booked')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='booker',null=True)
    venue=models.ForeignKey(Facility,related_name='venue',to_field='id',on_delete=models.CASCADE,null=True)
    venueName=models.CharField(max_length=50,null=True)
    venueId=models.IntegerField(null=True,default=0)
    isOverstayingCharged=models.BooleanField(null=True,default=False)
    def __str__(self) -> str:
        return f"REF NO:{self.referenceNo}"

walletAPI/models.py
from django.db import models
from wallet.models import User  # Import the User model from the "wallet" app
import uuid

class VendorTransaction(models.Model):

    # Choices for currency selection
    CURRENCY_CHOICES = (
        ('points', 'Points'),
        ('coins', 'Coins'),
    )

    # Custom UUID field with the "WILMS" prefix
    reference_code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    venueName=models.CharField(max_length=50,null=True)
    date=models.DateTimeField( auto_now_add=True)
    BookDate=models.DateField(null=True)
    startTime=models.TimeField(null=True)
    endTime=models.TimeField(null=True)
    purpose=models.CharField( max_length=50,default='Studying',)
    computers=models.IntegerField(default=0)
    total_cost = models.FloatField(default=0.0)
    currency = models.CharField(max_length=10, choices=CURRENCY_CHOICES, default='coins')

    # Foreign keys to User model from the "wallet" app
    customer = models.ForeignKey(User, on_delete=models.CASCADE)  # Assuming User is the customer

    
   

    def __str__(self):
        return str(self.reference_code)

walletAPI/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from urllib.parse import urlencode
from django.contrib.auth import authenticate, login
from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import generics
from .models import VendorTransaction
from .serializers import UserSerializer, VendorTransactionSerializer,LoginUserProfileInfoSerializer, LoginUserSerializer
from django.views.generic import TemplateView
from django.contrib.auth import logout

from wallet.models import UserProfileInfo
from rest_framework.authtoken.models import Token

from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from django.utils.decorators import method_decorator
from rest_framework.decorators import authentication_classes, permission_classes

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect

from django.shortcuts import render, redirect
from urllib.parse import urlencode  # Import urlencode to encode URL parameters


@csrf_protect
@api_view(['GET', 'POST'])
def login_view(request):
    if request.method == 'GET':
        # Serve the login form
        return render(request, 'login.html')

    elif request.method == 'POST':
        # Handle the login POST request
        email = request.POST.get('email')
        password = request.POST.get('password')

        if email and password:
            user = authenticate(request, email=email, password=password)
            if user:
                # Log the user in
                login(request, user)
                # Generate or retrieve an authentication token
                token, _ = Token.objects.get_or_create(user=user)

                # Encode the token as a query parameter
                token_param = urlencode({'token': token.key})

                # Redirect the user to the create transaction page with the token parameter
                redirect_url = f'/walletAPI/create-transaction/?{token_param}'
                return redirect(redirect_url)
        
        return JsonResponse({'detail': 'Invalid credentials.'}, status=status.HTTP_401_UNAUTHORIZED)




class CreateVendorTransactionView(generics.CreateAPIView):
    queryset = VendorTransaction.objects.all()
    serializer_class = VendorTransactionSerializer
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        return render(request, 'create-transaction.html')

    def perform_create(self, serializer):
        user = self.request.user
        currency = self.request.data.get('currency')
        transaction_amount = float(self.request.data.get('total_cost'))

        profile_info = UserProfileInfo.objects.get(user=user)

        if currency == 'coins':
            if profile_info.coin_balance >= transaction_amount:
                profile_info.coin_balance -= transaction_amount
                profile_info.save()
            else:
                return Response({'detail': 'Insufficient coins.'}, status=status.HTTP_400_BAD_REQUEST)
        elif currency == 'points':
            if profile_info.point_balance >= transaction_amount:
                profile_info.point_balance -= transaction_amount
                profile_info.save()
            else:
                return Response({'detail': 'Insufficient points.'}, status=status.HTTP_400_BAD_REQUEST)

        serializer.save(customer=user)

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)

        receipt_data = {
            'reference_code': serializer.data['reference_code'],
            'transaction_date': serializer.data['date'],
            'description': serializer.data['purpose'],
            'transaction_amount': serializer.data['total_cost'],
            'currency': self.request.data.get('currency'),
        }

        receipt_html = render(request, 'receipt.html', receipt_data)

        response_data = {
            'message': 'VendorTransaction created successfully',
            'reference_code': serializer.data['reference_code'],
            'user_id': self.request.user.id,
            'receipt_html': receipt_html.content.decode(),
        }

        return HttpResponse(receipt_html.content)
    

class TransactionReceiptView(TemplateView):
    template_name = 'receipt.html'


def logout_view(request):
    # Use Django's logout function to log the user out and clear the session
    logout(request)
    
    # Redirect the user to the login page or any other desired destination
    return redirect('walletAPI:login')  # Replace 'login' with the name of your login 




class CustomLoginAPIView(APIView):
    def post(self, request):
        email = request.data.get('email')
        password = request.data.get('password')

        user = authenticate(request, email=email, password=password)

        if user:
            if user.is_active:
                login(request, user)

                # Retrieve user profile information
                try:
                    user_profile = UserProfileInfo.objects.get(user=user)
                except UserProfileInfo.DoesNotExist:
                    user_profile = None

                user_data = UserSerializer(user).data

                if user_profile:
                    user_profile_data = LoginUserProfileInfoSerializer(user_profile).data
                else:
                    user_profile_data = {}

                # Combine the data into a single JSON response
                response_data = {
                    'user': user_data,
                    'user_profile': user_profile_data
                }

                return Response(response_data)
            else:
                return Response(status=status.HTTP_401_UNAUTHORIZED)
        else:
            return Response(status=status.HTTP_401_UNAUTHORIZED)

walletAPI/templates/create-transaction.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Vendor Transaction</title>
    <!-- Add links to Bootstrap CSS and JavaScript libraries -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/Login-Form-Basic-icons-1.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/Login-Form-Basic-icons.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}" />
  </head>
  <body class="bg-dark-subtle">
    <header></header>
    <div class="sticky-top bg-warning">
      <h1 class="fw-normal text-center text-bg-warning shadow">
        PAYMENT SCREEN
      </h1>
    </div>
    <div class="container mt-5">
      <div class="jumbotron">
        <form method="post" action="{% url 'walletAPI:create-transaction' %}">
          {% csrf_token %}

          <!-- Form fields -->

          <input
            type="hidden"
            id="customer"
            name="customer"
            value="{{ request.user.id }}"
            required
          />

          <div class="form-group">
            <label for="id_venueName"><strong>VENUE NAME:</strong></label>
            <input
              type="text"
              class="form-control"
              id="id_venueName"
              name="venueName"
              value="Coworking Space"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_date"><strong>TRANSACTION DATE:</strong></label>
            <input
              type="date"
              class="form-control"
              id="id_date"
              name="date"
              value="2023-11-08"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_startTime"><strong>START TIME:</strong></label>
            <input
              type="time"
              class="form-control"
              id="id_startTime"
              name="startTime"
              value="12:00:00"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_endTime"><strong>END TIME:</strong></label>
            <input
              type="time"
              class="form-control"
              id="id_endTime"
              name="endTime"
              value="13:00:00"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_officeName"><strong>OFFICE NAME:</strong></label>
            <input
              type="text"
              class="form-control"
              id="id_officeName"
              name="officeName"
              value="WIL"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_purpose"><strong>PURPOSE:</strong></label>
            <input
              type="text"
              class="form-control"
              id="id_purpose"
              name="purpose"
              value="Studying"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_computers"><strong>NO. OF COMPUTERS:</strong></label>
            <input
              type="number"
              class="form-control"
              id="id_computers"
              name="computers"
              value="2"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_total_cost"><strong>TOTAL COST:</strong></label>
            <input
              type="number"
              step="0.01"
              class="form-control"
              id="id_total_cost"
              name="total_cost"
              value="6"
              required
            />
          </div>

          <div class="form-group">
            <label for="id_currency"><strong>CURRENCY:</strong></label>
            <select
              class="form-control"
              id="id_currency"
              name="currency"
              required
            >
              <option value="points" selected>Points</option>
              <option value="coins">Coins</option>
            </select>
          </div>

          <!-- Button to show confirmation modal -->
          <button
            type="button"
            id="showConfirmationModal"
            class="btn btn-primary btn-block"
          >
            <strong>MAKE PAYMENT</strong>
          </button>

          <!-- Submit button (hidden) -->
          <input
            type="submit"
            style="display: none"
            id="submitTransactionForm"
          />
        </form>
      </div>

      <!-- Modal for confirmation -->
      <div
        class="modal fade"
        id="confirmationModal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">
                Confirm Payment
              </h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <!-- Display confirmation data here -->
              <p>
                <strong>VENUE NAME:</strong>
                <span id="confirmationVenueName"></span>
              </p>
              <p>
                <strong>TRANSACTION DATE:</strong>
                <span id="confirmationDate"></span>
              </p>
              <p>
                <strong>START TIME:</strong>
                <span id="confirmationStartTime"></span>
              </p>
              <p>
                <strong>END TIME:</strong>
                <span id="confirmationEndTime"></span>
              </p>
              <p>
                <strong>OFFICE NAME:</strong>
                <span id="confirmationOfficeName"></span>
              </p>
              <p>
                <strong>PURPOSE:</strong>
                <span id="confirmationPurpose"></span>
              </p>
              <p>
                <strong>NO. OF COMPUTERS:</strong>
                <span id="confirmationComputers"></span>
              </p>
              <p>
                <strong>TOTAL COST:</strong>
                <span id="confirmationTotalCost"></span>
              </p>
              <p>
                <strong>CURRENCY:</strong>
                <span id="confirmationCurrency"></span>
              </p>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                Cancel
              </button>
              <button
                type="button"
                id="confirmTransaction"
                class="btn btn-primary"
              >
                Confirm
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Add links to Bootstrap JavaScript and jQuery libraries -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        function updateCreateButton() {
          const venueName = document.getElementById("id_venueName").value;
          const transactionDate = document.getElementById("id_date").value;
          const startTime = document.getElementById("id_startTime").value;
          const endTime = document.getElementById("id_endTime").value;
          const officeName = document.getElementById("id_officeName").value;
          const purpose = document.getElementById("id_purpose").value;
          const computers = document.getElementById("id_computers").value;
          const totalCost = document.getElementById("id_total_cost").value;
          const currency = document.getElementById("id_currency").value;

          const createButton = document.getElementById("showConfirmationModal");
          createButton.disabled = !(
            venueName &&
            transactionDate &&
            startTime &&
            endTime &&
            officeName &&
            purpose &&
            computers &&
            totalCost &&
            currency
          );
        }

        // Function to fill the modal fields with entered form data
        function fillConfirmationModal() {
          document.getElementById("confirmationVenueName").textContent =
            document.getElementById("id_venueName").value;
          document.getElementById("confirmationDate").textContent =
            document.getElementById("id_date").value;
          document.getElementById("confirmationStartTime").textContent =
            document.getElementById("id_startTime").value;
          document.getElementById("confirmationEndTime").textContent =
            document.getElementById("id_endTime").value;
          document.getElementById("confirmationOfficeName").textContent =
            document.getElementById("id_officeName").value;
          document.getElementById("confirmationPurpose").textContent =
            document.getElementById("id_purpose").value;
          document.getElementById("confirmationComputers").textContent =
            document.getElementById("id_computers").value;
          document.getElementById("confirmationTotalCost").textContent =
            document.getElementById("id_total_cost").value;
          document.getElementById("confirmationCurrency").textContent =
            document.getElementById("id_currency").value;
        }

        // Show the confirmation modal on button click
        document
          .getElementById("showConfirmationModal")
          .addEventListener("click", function () {
            fillConfirmationModal();
            $("#confirmationModal").modal("show");
          });

        // Confirm transaction action
        document
          .getElementById("confirmTransaction")
          .addEventListener("click", function () {
            document.getElementById("submitTransactionForm").click(); // Trigger form submission
          });

        // Add input listeners to form fields for enabling/disabling the button
        document
          .getElementById("id_venueName")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_date")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_startTime")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_endTime")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_officeName")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_purpose")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_computers")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_total_cost")
          .addEventListener("input", updateCreateButton);
        document
          .getElementById("id_currency")
          .addEventListener("change", updateCreateButton);

        updateCreateButton(); // Initial state update
      });
    </script>
  </body>
</html>

walletAPI/templates/login.html
{% load static %}
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <title>login(vendor)</title>
    <link
      rel="stylesheet"
      href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/Login-Form-Basic-icons-1.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/Login-Form-Basic-icons.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}" />
  </head>

  <body class="bg-dark-subtle">
    <header></header>
    <h1 class="fw-normal text-center text-bg-warning shadow">PAYMENT SCREEN</h1>
    <section class="position-relative py-4 py-xl-5">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="col-md-6 col-xl-4">
            <div class="card mb-5">
              <div class="card-body d-flex flex-column align-items-center">
                <img
                  src="{% static 'assets/img/w1_yellow.70f997970da5.png' %}"
                  width="617"
                  height="255"
                  style="padding-bottom: 0px; margin-bottom: 22px"
                />
                <form
                  class="text-center"
                  method="post"
                  action="{% url 'walletAPI:login' %}"
                >
                  {% csrf_token %}
                  <div class="mb-3">
                    <input
                      class="form-control"
                      type="email"
                      name="email"
                      placeholder="Email"
                    />
                  </div>
                  <div class="mb-3">
                    <input
                      class="form-control"
                      type="password"
                      name="password"
                      placeholder="Password"
                    />
                  </div>
                  <div class="mb-3">
                    <button class="btn btn-primary d-block w-100" type="submit">
                      Login
                    </button>
                  </div>
                  <p class="text-muted">Forgot your password?</p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>